# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipelineCon'
    subscriptionId: '501dca37-c84d-4939-96be-b6c113a26721'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azurepipeline-rg'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFileLink: 'https://raw.githubusercontent.com/acdcaz/AzureRmPipeline-repo/main/CreateWebApp/AzureDeploy.json'
    overrideParameters: '-projectName AzureArmDeployment -linkedTemplateURI https://raw.githubusercontent.com/acdcaz/AzureRmPipeline-repo/main/CreateWebApp/LinkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'davesDeployment'
